# Generated by Django 5.0.4 on 2024-04-18 23:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import brackets.models


class Migration(migrations.Migration):
    dependencies = [
        ("brackets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name to identify the bracket.", max_length=100
                    ),
                ),
                (
                    "random_seed",
                    models.BigIntegerField(
                        default=brackets.models.generate_random_seed,
                        help_text="The seed used to prime the random number generator for the bracket predictor.",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns the bracket.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        related_query_name="bracket",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
